### ISSUE TITLE
html to crel

### ISSUE THREAD

**Issue by bazjapan** [KoryNunn/crel#19]
Hello, just started dabbling with crel. Thanks - great tool.
Just wondering if anyone has made a utility to convert html to crel code.
I have a few views I'd like to try and convert.

Was looking at this http://www.jsonml.org/, which seems to be a good start;
Hope I'm not trying to  reinvent the wheel here.

**Comment by bazjapan** [comment]
this scratched the itch for now.
$(document).ready(function() {

  var html = $("body").find(".bx_box")[0].innerHTML.trim();
  var parsed = JsonML.fromHTMLText(html);
  
  var get_crel_obj = function(array){
    var ready = [];
    var txt = "crel('"+array[0].toLowerCase()+"',";
    for(var i = 1; i<array.length; i++){
      var item = array[i];
      if (Array.isArray(item)) {
        ready.push(get_crel_obj(item));
      }else{
        if(typeof item == 'string' || item instanceof String){
          if (item.trim()) {
            ready.push(JSON.stringify(item));
          }
        }else{
          ready.push(JSON.stringify(item));
        }
      }
    }
    txt += ready.join(",");
    txt+=")";
    return txt;
  }
  
  
  console.log(get_crel_obj(parsed));

})

**Comment by KoryNunn** [comment]
I have a repo with a few converters, here is the DOM to crel one: https://github.com/KoryNunn/dom-to-js/blob/master/toCrel.js

**Comment by bazjapan** [comment]
nice one thanks
