### ISSUE TITLE
onfocusout / onchange etc. issue

### ISSUE THREAD

**Issue by filmackay** [KoryNunn/crel#23]
On Chrome at least (only tested that so far), the following works fine:

```
    valueEdit = crel('input', {
      type: 'text'
    });
    valueEdit.onblur=function(){console.log('zzz');};
```

However, this one returns an error `Uncaught SyntaxError: Unexpected token (` line 1:

```
    valueEdit = crel('input', {
      type: 'text',
      onblur: function(){console.log('zzz');}
    });
```

Many events (like onclick) work fine, but not the others. Interestingly, the Chrome debugger shows onblur as `undefined` in the non-working case, whereas it is obviously correctly referring to an anonymous function in the working case.

Is this a crel bug?

**Comment by KoryNunn** [comment]
Not exactly. Crel uses setAttribute under the covers for all settings. The behavior you are seeing is just what the browser does for that key.

I can't recommend you assign handlers to properties on an element, a more robust way is to use `element.addEventListener('blur', function (event){...})`

You can extend crel using the attrMap api document in the readme.
