### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by maciejhirsz** [KoryNunn/crel#25]
> crel is fast. Depending on what browser you use, it is up there with straight document.createElement calls.

That part of the README seems to date back to 2012, the jsperf link is dead because jsperf is dead, so I can't really see the numbers there. 

I've been fixing performance in FRZR and RE:DOM lately, and I'm writing my own little DOM library for personal uses / research, and out of curiosity I run crel through a small benchmark of mine.

Relevant numbers:

```
Benching Vanilla JS <div> with children
5103ns per iteration (195962 ops/sec)

Benching Crel <div> with children
19319ns per iteration (51762 ops/sec)
```

Relevant codes:

``` js
bench('Vanilla JS <div> with children', function() {
    var div = document.createElement('div');

    var header = document.createElement('h1');
    header.className = 'voo-header';

    var b = document.createElement('b');
    b.textContent = 'Voo';

    header.textContent = 'Hello ';
    header.appendChild(b);
    header.appendChild(document.createTextNode('!'));

    div.appendChild(header);

    var p = document.createElement('p');
    p.textContent = 'Bacon ipsum dolor amet meatloaf meatball shank porchetta \
             picanha bresaola short loin short ribs capicola fatback beef \
             ribs corned beef ham hock.';

    div.appendChild(p);
});

bench('Crel <div> with children', function() {
    crel('div',
        crel('h1', { className: 'crel' }, 'Hello ', crel('b', 'Voo'), '!'),
        crel('p',
            'Bacon ipsum dolor amet meatloaf meatball shank porchetta \
             picanha bresaola short loin short ribs capicola fatback beef \
             ribs corned beef ham hock.'
        )
    )
});
```

Given what `crel` does, and all my various experiments, numbers closer to 7000-8000ns on my hardware should have been expected. Are you interested in PRs trimming some of the unnecessary overhead?

**Comment by KoryNunn** [comment]
Thanks, I'd love to see a PR.

I'd consider dropping old IE support and per=property handling in a new major version which would clean up the internals significantly.

**Comment by KoryNunn** [comment]
Closing as stale, still interested in perf improvements :)
