### ISSUE TITLE
Parse Embedded Id and Classes

### ISSUE THREAD

**Issue by GCSBOSS** [KoryNunn/crel#29]
It would be very nice to have `#hash-like` id and `.dot-like` classes parsed on tag string. 

Eg.:
```
crel(document.body, 
    crel('input.cool'),
    crel('button#login')
);
```

**Comment by KoryNunn** [comment]
Hi,

Thanks for the suggestion. Crel is designed to be as small, fast, and simple as possible. It would be trivial to write a module that uses crel as a dependencey to achieve these features, which would give users the option, and I'd encourage you to build it. I'd be happy to give you a hand if you wanted.

Thanks.

**Comment by KoryNunn** [comment]
This interested me enough to make a gist: http://requirebin.com/?code=02dfb8a409fc97e6921c
