### ISSUE TITLE
Event handlers

### ISSUE THREAD

**Issue by DevBonBon** [KoryNunn/crel#30]
I'd be willing to add event handler creation to the utility (using addEventListener). Would that be a feature you'd think fits the project? If so, what kind of syntax should it have?

**Comment by KoryNunn** [comment]
I've considered this previously, but I don't think this is the right layer for it.

I would probably look at making a layer on top that has niceties like that. The goal of crel is to be as lightweight and fast as possible.

An example of a lib that supports event binding (and way more) is fastn: https://github.com/KoryNunn/fastn

An example of how it does event binding is here: https://goo.gl/Ki2h4J

But, this also points out to me that there is some documentation missing for all of how this feature works in fastn, as it accounts for things like whether or not to bind at bubble or capture phase, and allows multiple events to be bound to at once:

EG:

```
fastn('input').on('change input keypress', handleInputChange);
```

**Comment by KoryNunn** [comment]
Readme updated.
