### ISSUE TITLE
crel fails to add children to iframe document

### ISSUE THREAD

**Issue by keturn** [KoryNunn/crel#48]
If you put an iframe on a page and do a little something like this:

```.js
var innerBody = document.getElementsByTagName("iframe")[0].contentDocument.body;
crel(innerBody, crel("h1", "hi"))
```

In Chrome 72, it will error with
> Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('[object HTMLBodyElement]') is not a valid name.

(It succeeds without issue in Firefox 65.)

This is due to the check where crel is trying to figure out if its argument is a node or not (see related issue #11).

In Chrome

* innerBody instanceof iframe.contentWindow.Element == true :heavy_check_mark: 
* innerBody instanceof window.Element == false :x: 

I expect this is an uncommon edge case, and I very much appreciate crel's dedication to keeping its implementation compact and interface simple, so I'd understand if this is a *wontfix*, but I figured it's worth documenting.

If we do want to fix this, I think the thing to do is provide a way to change which `window` crel uses to get `Element` and `Node` and `document`.

(Perhaps surprisingly, doing `innerBody.appendChild` _does_ work with elements created using the outer document. At least with these two specific browser versions and document types. But I expect it would be safer, and easier to pass type checks, if the `createElement` were called on the document the elements are intended to be appended to.)

**Comment by KoryNunn** [comment]
Hmm... Are you sure it's possible to add an element to an iFrame from the parent frame? I'd hazard a guess that it isn't.

Would you be able to check this?

**Comment by keturn** [comment]
It is, I have it working in practice here. It's subject to some cross-origin restrictions _if_ the iframe's origin different than its parent's, but once you have a reference to the frame's `contentDocument` it works as you'd expect.

**Comment by KoryNunn** [comment]
Do you need to do `contentDocument.createElement()` to be able to append it to the contentDocument? If so, you should be able to solve this with a wrapper around crel that takes the contentDocument as an initialisation, and creates elements before passing them in.

This does not solve the error you are seeing, but I believe it will solve the next problem you would run into.

**Comment by KoryNunn** [comment]
so `isElement` is the check that is failing here, it is exposed at `crel.isElement` which means you can overwrite it for your use case. Your case should be fully achievable with just a wrapper, and no modifications to crel.

**Comment by KoryNunn** [comment]
@keturn How did you go with this? Were you able to solve this without modification to crel?

**Comment by KoryNunn** [comment]
I'm going to close this as stale, feel free to kick it off again if there is any more info.
