### ISSUE TITLE
is there any breaking change from 4.0.1 to 4.2.0?

### ISSUE THREAD

**Issue by xerosanyam** [KoryNunn/crel#56]
Please add changelog or release notes to the repo!
Thanks for the hard work.

**Comment by KoryNunn** [comment]
Hey, you can always see what change by looking at the commit log: https://github.com/KoryNunn/crel/commits/master

You can also know if there has been a breaking change by looking at how the version incremented: https://semver.org/

In the case of the last version, it was a minor version change, meaning something was added, but nothing is broken by the change.

**Comment by KoryNunn** [comment]
Here I made this: https://changelogit.korynunn.com/#korynunn/crel
