### ISSUE TITLE
Unnecessarily lost IE11 support

### ISSUE THREAD

**Issue by marijnh** [KoryNunn/crel#57]
Patch https://github.com/KoryNunn/crel/commit/541459191c94f1fe09cc531fecc49b6d3ed4a6ad removes the check for `Proxy` support, breaking this library on IE11. Was the goal here just to save a single line of code? Could we maybe revert it?

**Comment by KoryNunn** [comment]
I'd be happy to re-add this if you wouldn't mind preparing a PR?

**Comment by marijnh** [comment]
See #58
